### ISSUE TITLE
How to jump to a particular page in PDF, when you open it.

### ISSUE THREAD

**Issue by angad305** [afreakyelf/Pdf-Viewer#111]
Can i jump to a particular page, like to a last saved page position which i can save using "onPageChanged" , so when i reopen the same PDF, i can jump to that particular page, instead of scrolling. i couldn't find method to achieve that. am i missing something?

**Comment by afreakyelf** [comment]
Hey angad, are you rendering your PDF in a view or using PdfViewerActivity to open the pdf?

**Comment by angad305** [comment]
Rendering pdf in a view

**Comment by afreakyelf** [comment]
Hi, The Above issue has been fixed in new release. https://github.com/afreakyelf/Pdf-Viewer/releases/tag/v2.1.0

Please migrate to Maven central. More here: https://github.com/afreakyelf/Pdf-Viewer/releases/tag/v2.1.0

Thank you for using the library. Please reopen/raise a new issue if you still face this error.

I have added `jumpToPage` method. Check `MainActivity` for usecase.

Join our [discord](https://discord.gg/z9qQSHMxSR) for more updates!
